edition             = "2018"
format_macro_bodies = true
format_strings      = true
merge_imports       = true
reorder_impl_items  = true
reorder_imports     = true
reorder_modules     = true
wrap_comments       = true
